#+TITLE: Emacs Configuration
#+AUTHOR: M.Metz

The emacs-lisp code in this file will run when emacs starts. A great use case
for [[https://en.wikipedia.org/wiki/Literate_programming]['literate programming']] imho.

* Installing Emacs

On macOS, I use [[http://brew.sh/][homebrew]] to install emacs.

Check "brew info emacs" to see if install options are still valid.

#+begin_src sh
brew install emacs --build-from-source --with-cocoa --with-gnutls --with-imagemagick@6
#+end_src

- ~--build-from-source~ to prevent dependency problem with jpeg library
- ~-with-cocoa~ to enable the emacs.app
- ~--with-gnutls~ to enable setting up secure communication
- ~--with-imagemagick@6~ to work with images

Create a symbolic link to emacs from the application directory:

#+begin_src sh
ln -s /usr/local/Cellar/emacs/25.3/Emacs.app ~/Applications/
#+end_src


* Override standard emacs behaviour

** UI

*** (No) Menu & (no) scroll bar

I have never felt the need to use the menu or the scroll bar in emacs.

#+begin_src emacs-lisp
(tool-bar-mode 0)
(menu-bar-mode 0)
(when window-system
  (scroll-bar-mode -1))
(setq scroll-conservatively 100)
#+end_src

The 'scroll-conservatively' makes sure emacs doesn't recenter the cursor after
scrolling.

*** Window Size

I like this as a default size for my emacs app window:

#+begin_src emacs-lisp
(when window-system
  (set-frame-size (selected-frame) 112 64))
#+end_src

Keybindings to resize windows within emacs app window:

#+begin_src emacs-lisp
(bind-key "s-C-<left>"  'shrink-window-horizontally)
(bind-key "s-C-<right>" 'enlarge-window-horizontally)
(bind-key "s-C-<down>"  'shrink-window)
(bind-key "s-C-<up>"    'enlarge-window)
#+end_src

Unfortunately, the order of the '(no) menu & (no) scroll bar' paragraph and the
'window size' paragraph is important. If you change the order (window size
first), the window size will be the standard emacs window size, not the
specified size.

*** Highlight current line

Softly highlight the current line:

#+begin_src emacs-lisp
(when window-system
  (global-hl-line-mode))
#+end_src

*** Disable annoying (visible) bells

[[http://stackoverflow.com/questions/11679700/emacs-disable-beep-when-trying-to-move-beyond-the-end-of-the-document][Disable Annoying Alarms]]

#+begin_src emacs-lisp
(defun my-bell-function ())
(setq ring-bell-function 'my-bell-function)
(setq visible-bell nil)
#+end_src


** Sensible defaults

I use [[https://github.com/hrs/sensible-defaults.el][sensible defaults]] for some basic settings.

#+begin_src emacs-lisp
(load-file "~/.emacs.d/sensible-defaults.el")
(sensible-defaults/use-all-settings)
(sensible-defaults/use-all-keybindings)
(sensible-defaults/backup-to-temp-directory)
#+end_src

(load-file needs the complete path because emacs can be started from any
location on the terminal. In that case relative paths won't work)


** Recent Files

Build a list of recently used files, easily accessible via the "C-x C-r" keybinding.

#+begin_src emacs-lisp
(recentf-mode 1)
(setq recentf-max-menu-items 32)
(global-set-key (kbd "C-x C-r") 'recentf-open-files)
#+end_src


* Packages

This configuration uses the [[https://github.com/jwiegley/use-package][use-package]] package from John Wiegley.

** Smex

Smex adds history and suggestions to M-x

#+begin_src emacs-lisp
(use-package smex
  :ensure t
  :bind (("M-x"         . smex)
         ("M-X"         . smex-major-mode-commands)
         ("C-c C-c M-x" . execute-extended-command)))
#+end_src

Main Usage:

| Keybinding  | Description                                       |
|-------------+---------------------------------------------------|
| M-x         | Same as old M-x but with history & suggestions    |
| M-X         | Only show commands relevant to current major mode |
| C-c C-c M-x | Link to old M-x command                           |
|-------------+---------------------------------------------------|
| C-h w       | 'Where is' - shows kbd for selected command       |
| C-h f       | Runs 'describe Function' on selected command      |
| M-.         | Jumps to definition of selected command           |
|-------------+---------------------------------------------------|

** Neotree

Neotree shows your directories and files in a tree view.

#+begin_src emacs-lisp
(use-package neotree
  :ensure t
  :bind (("<f8>" . neotree-toggle)))
#+end_src

Main Usage:

| Keybinding | Description                      |
|------------+----------------------------------|
| f8         | Toggle neotree                   |
|------------+----------------------------------|
| g          | Refresh neotree                  |
| H          | Toggle display hidden files      |
|------------+----------------------------------|
| C-c C-n    | Create a new file or directory   |
| C-c C-d    | Delete a file or directory       |
| C-c C-r    | Rename a file or directory       |
| C-c C-c    | Change root directory to display |
|------------+----------------------------------|

** Engine-Mode

Engine-mode allows me to do internet searches on configured search engines.

#+BEGIN_SRC emacs-lisp
(use-package engine-mode
  :ensure t)

;; enable engine-mode globally
(engine-mode t)

(defengine amazon
  "https://www.amazon.com/s/ref=nb_sb_noss?field-keywords=%s"
  :keybinding "a")

(defengine dictionary
  "http://www.dictionary.com/browse/%s"
  :keybinding "d")

(defengine google
  "http://www.google.com/search?ie=utf-8&oe=utf-8&q=%s"
  :keybinding "g")

(defengine github
  "https://github.com/search?ref=simplesearch&q=%s"
  :keybinding "h")

(defengine google-images
  "http://www.google.com/images?hl=en&source=hp&biw=1440&bih=795&gbv=2&aq=f&aqi=&aql=&oq=&q=%s"
  :keybinding "i")

(defengine google-maps
  "http://maps.google.com/maps?q=%s"
  :keybinding "m")

(defengine qwant
  "https://www.qwant.com/?q=%s"
  :keybinding "q")

(defengine stack-overflow
  "https://stackoverflow.com/search?q=%s"
  :keybinding "s")

(defengine google-translate
  "https://translate.google.com/#auto/en/%s"
  :keybinding "t")

(defengine wikipedia
  "http://www.wikipedia.org/search-redirect.php?language=en&go=Go&search=%s"
  :keybinding "w")

(defengine youtube
  "http://www.youtube.com/results?aq=f&oq=&search_query=%s"
  :keybinding "y")
#+END_SRC

Main usage:

C-x / <key for your engine here> for invoking engine-mode

If your cursor is on a word when invoking engine-mode, that word will
be the default search value unless you overwrite it by typing another
search term.

If you have selected a piece of text (C-SPC ...) and invoke
engine-mode, that piece of text will be your search string.

So for instance I want to search for "emil ernebro" on youtube:

- C-x / y
- type "emil ernebro"
- engine-mode will open youtube and search for emil ernebro

Other way to search for "emil ernebro", this time on google-images:

- Select "emil ernebro" in the current textbuffer
- C-x / i

** Magit

Magit is a brilliant interface to git. It provides several 'popups' (like
commit, push, log, diff) which guide you through the (git) options.

#+begin_src emacs-lisp
(use-package magit
  :ensure t
  :bind (("C-c g" . magit-status)))
#+end_src

Main Usage:

| Keybinding | Description                         |
|------------+-------------------------------------|
| C-c g      | (ma)git status                      |
|------------+-------------------------------------|
| h          | list all popups + commands          |
| g          | Refresh                             |
| n          | Next section                        |
| p          | Previous section                    |
| TAB        | expand or collapse section at point |
|------------+-------------------------------------|
| s          | stage                               |
| u          | unstage                             |
| c          | commit popup                        |
| C-c C-c    | really commit                       |
| P          | push popup                          |
| u          | push to upstream                    |
|------------+-------------------------------------|

** RestClient

I'm using Restclient to test REST calls from text files.
Additional info on [[https://github.com/pashky/restclient.el][github]] (including examples)

#+begin_src emacs-lisp
(use-package restclient
  :ensure t)
#+end_src

Main Usage:

| Keybinding | Description                                      |
|------------+--------------------------------------------------|
| C-c C-c    | runs query under cursor, switch to result window |
| C-c C-v    | runs query under cursor, stays in current window |
| C-c C-p    | jump to previous query                           |
| C-c C-n    | jump to next query                               |
| C-c C-.    | mark the query under the cursor                  |
| C-c C-u    | copy query under the cursor as curl cmd          |
|------------+--------------------------------------------------|

** Markdown

Use markdown mode, also for my foldingtext files

#+begin_src emacs-lisp
(use-package markdown-mode
  :ensure   t
  :commands (markdown-mode gfm-mode)
  :mode     (("README\\.md\\'" . gfm-mode)
             ("\\.md\\'"       . markdown-mode)
             ("\\.markdown\\'" . markdown-mode)
             ("\\.ft\\'"       . markdown-mode))
  :init     (setq markdown-command "multimarkdown"))
#+end_src


* Debugging

Sometimes adding a package doesn't work as expected. In those cases you can try
several things:

- Try starting emacs from the terminal with ~emacs --debug-init~
- Set ~use-package-verbose~ to ~t~ . Errors occuring while initializing or
  configuring a package will not stop emacs from loading. With this setting the
  errors will be reported to a special ~*Warnings*~ popup buffer so you can debug
  the package loading.
- Try ~package-refresh-contents~ or check if the troublesome package is in
  ~package-list-packages~
