#+TITLE: Emacs Configuration
#+AUTHOR: M.Metz

This configuration uses the [[https://github.com/jwiegley/use-package][use-package]] package from John Wiegley.

* Installing Emacs

On macOS, I use [[http://brew.sh/][homebrew]] to install emacs.

Check "brew info emacs" to see if install options are still valid.

#+begin_src sh
brew install emacs --build-from-source --with-cocoa --with-gnutls --with-imagemagick@6
#+end_src

- build-from-source to prevent dependency problem with jpeg library
- cocoa to enable the emacs.app
- gnutls to enable setting up secure communication
- imagemagick to work with images

I also create a symbolic link to emacs:

#+begin_src sh
ln -s /usr/local/Cellar/emacs/25.3/Emacs.app ~/Applications/
#+end_src

* Sensible defaults

I use [[https://github.com/hrs/sensible-defaults.el][sensible defaults]] for
some basic settings.

load-file needs the complete path because emacs could be started from
anywhere on the terminal.

#+begin_src emacs-lisp
(load-file "~/.emacs.d/sensible-defaults.el")
(sensible-defaults/use-all-settings)
(sensible-defaults/use-all-keybindings)
(sensible-defaults/backup-to-temp-directory)
#+end_src

* Disable annoying (visible) bells

[[http://stackoverflow.com/questions/11679700/emacs-disable-beep-when-trying-to-move-beyond-the-end-of-the-document][Disable Annoying Alarms]]

#+begin_src emacs-lisp
(defun my-bell-function ())
(setq ring-bell-function 'my-bell-function)
(setq visible-bell nil)
#+end_src

* Sizes

I like this as a default size for my emacs app window:

#+begin_src emacs-lisp
(if (window-system) (set-frame-size (selected-frame) 112 64))
#+end_src

* Packages

** Smex

Smex adds history and suggestions to M-x

#+begin_src emacs-lisp
(use-package smex
  :ensure t
  :bind (("M-x"         . smex)
         ("M-X"         . smex-major-mode-commands)
         ("C-c C-c M-x" . execute-extended-command)))
#+end_src

Main Usage:

| Keybinding  | Description                                       |
|-------------+---------------------------------------------------|
| M-x         | Same as old M-x but with history & suggestions    |
| M-X         | Only show commands relevant to current major mode |
| C-c C-c M-x | Link to old M-x command                           |
|-------------+---------------------------------------------------|
| C-h w       | 'Where is' - shows kbd for selected command       |
| C-h f       | Runs 'describe Function' on selected command      |
| M-.         | Jumps to definition of selected command           |
|-------------+---------------------------------------------------|

** Neotree

Neotree shows your directories and files in a tree view.

#+begin_src emacs-lisp
(use-package neotree
  :ensure t
  :bind (("<f8>" . neotree-toggle)))
#+end_src

Main Usage:

| Keybinding | Description                      |
|------------+----------------------------------|
| f8         | Toggle neotree                   |
|------------+----------------------------------|
| g          | Refresh neotree                  |
| H          | Toggle display hidden files      |
|------------+----------------------------------|
| C-c C-n    | Create a new file or directory   |
| C-c C-d    | Delete a file or directory       |
| C-c C-r    | Rename a file or directory       |
| C-c C-c    | Change root directory to display |
|------------+----------------------------------|

** Next Package
